### ISSUE TITLE
Калькулятор завершает свою работу если введена неизвестная переменная

### ISSUE THREAD

**Issue by i582** [Tsygankov-Slava/Calculator#2]
## Введенная команда

```
>>> name
```

## Актуальное поведение

<img width="574" src="https://user-images.githubusercontent.com/51853996/169570883-5a76aa63-8905-4430-b83e-6deef8dd8080.png">

## Ожидаемое поведение

Сообщение что переменная не найдена

**Comment by i582** [comment]
Такое же поведение наблюдается и для неизвестных функций.

**Comment by Tsygankov-Slava** [comment]
Added validation of undefined variables and functions for the input string.

If you have written a function or variable, which isn't defined, the program will send an error.
